export const ErrorCodes = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	FORBIDDEN: 'FORBIDDEN',
	BAD_REQUEST: 'BAD_REQUEST',
	NOT_FOUND: 'NOT_FOUND',
	RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	DATABASE_ERROR: 'DATABASE_ERROR',
	SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
	CLIENT_ERROR: 'CLIENT_ERROR',
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
} as const

export const getErrorCodeByStatusCode = (statusCode: number) => {
	const errorCodes: Record<number, string> = {
		400: ErrorCodes.BAD_REQUEST,
		401: ErrorCodes.UNAUTHORIZED,
		403: ErrorCodes.FORBIDDEN,
		404: ErrorCodes.NOT_FOUND,
		429: ErrorCodes.RATE_LIMIT_EXCEEDED,
		500: ErrorCodes.INTERNAL_ERROR
	}
	return errorCodes[statusCode] || ErrorCodes.SERVICE_UNAVAILABLE
}

export type ErrorCode = keyof typeof ErrorCodes
