export const ErrorCodes = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	DATABASE_ERROR: 'DATABASE_ERROR',
	SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
} as const

export type ErrorCode = keyof typeof ErrorCodes
