export { AuthController } from './auth.controller'
export { MovieController } from './movie.controller'
export { SubtitleController } from './subtitle.controller'
export { TranslateController } from './translate.controller'
export { UserController } from './user.controller'
export { WordController } from './word.controller'
