export { Auth } from './Auth/Auth'
export { Main } from './Main/Main'
export { Movie } from './Movie/Movie'
export { Popular } from './Popular'
export { Profile } from './Profile'
export { Search } from './Search'
