export { Auth } from './Auth/Auth'
export { Main } from './Main/Main'
export { MovieSubtitles } from './MovieSubtitles/MovieSubtitles'
export { Popular } from './Popular'
export { Profile } from './Profile'
export { Search } from './Search'
